language: cpp
sudo: required

cache:
  ccache: true
  directories:
    - .ccache
    - ${TRAVIS_BUILD_DIR}/deps

python:
  - "3.5"

services:
  - docker

matrix:
  fast_finish: true
  include:
    - compiler: "gcc"
      os: osx
      osx_image: xcode9.2
    - compiler: "gcc"
      os: osx
      osx_images: xcode10.1
    - compiler: "gcc"
      os: linux
      dist: trusty
    - compiler: "gcc"
      os: linux
      dist: xenial
    - os: linux
      env:
        - OS_TYPE=ubuntu_docker
        - OS_VERSION=bionic
    - os: linux
      env:
        - OS_TYPE=ubuntu_flatpak_docker
        - OS_VERSION=bionic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./CI/travis/before_install_darwin.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./CI/travis/before_install_linux.sh "$OS_TYPE" "$OS_VERSION" ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_linux.sh scopy "$OS_TYPE" "$OS_VERSION" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_darwin.sh ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ${TRAVIS_BUILD_DIR}/build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/package_darwin.sh; fi


notifications:
  email:
    on_success: change
    on_failure: always

before_deploy:
  - . ${TRAVIS_BUILD_DIR}/CI/travis/before_deploy.sh
